### ISSUE TITLE
Keep getting unknown scheme "C"

### ISSUE THREAD

**Issue by ammarzakwan-cell** [flow-php/flow#1047]
source code: 

`
$rows = data_frame()
            ->read(from_csv(ROOT_PATH . '/storage/SampleCSVFile_2kb.csv'))
            ->fetch();

        dd($rows);`
        
getting csv sample from here to test
https://sample-videos.com/download-sample-csv.php

after run in console im getting this error unknown scheme "C"

if i try this path

`$rows = data_frame()
            ->read(from_csv('storage/SampleCSVFile_2kb.csv'))
            ->fetch();`
            
i will get: Invalid uri: file://C:\laragon\www\etl_test\storage

**Comment by norberttech** [comment]
Hey! 
Yeah, Windows is not getting along with Flow but you can try what I suggested [here](https://github.com/flow-php/flow/issues/1011#issuecomment-1992741189). 
I'm working on preparing a windows development environment for myself so I might be able to came up with a more automated solution for that issue since it was already reported twice. 
Let me know if what I suggested worked for you!

**Comment by ammarzakwan-cell** [comment]
thank you @norberttech, its working, you are correct this thing related to windows path.
