### ISSUE TITLE
Question, about etl proces xml to json

### ISSUE THREAD

**Issue by Pin0** [flow-php/flow#459]
I'm building my own extractor that parses xml and have the following snippet

```
public function extract(FlowContext $context) : \Generator
    {
        $client = new Client(); //new client that gives me xml records
        foreach ($client->fetchRecords() as $record) { //fetchRecords is a generator $record is a simpleXmlElement Object
            unset($rows); //If I don't do this it will have exponentially high json records when written to json
            $rows[] = new Row(new Row\Entries(Entry::object('xml_record', $record))); // so this will add all Rows to $rows and not just the new ones.
            yield new Rows(...$rows);
        }
    }
}
```

My question is: Am I doing this right? It feels wrong to unset $rows

**Comment by norberttech** [comment]
hey @Pin0, sorry for the late response, could you maybe let me know why do you need to build your own XML Extractor? Flow PHP comes with a builtin [XML Adapter](https://github.com/flow-php/etl-adapter-xml)

If the default one is not working for you, could you maybe elaborate on what is missing so we can adjust it? 
Otherwise, you can always look at the existing adapter and get some inspiration for building your own.

**Comment by Pin0** [comment]
It actually parses XML/rdf coming from a tripple store. So I'm trying to use the easyrdf PHP library to parse those triples properly. 
I took a look at the xml adapter and the extractor there also initializes $rows to an empty array inside the foreach of the extract method. 
So I guess I should do that as well (looks better then unsetting $rows) 

My question was more about the fact of the exponentially growing of Rows when not unsetting or initializing. Probably because I don't exactly understand something yet... :-)

**Comment by norberttech** [comment]
oh I see, so let me explain a bit the design behind extractors/transformers. 

**Extractor**
The only role of an extractor is to iteratively extract data from any kind of data source, and yield it as a `Rows`. 
So let say, you have a JSON/XML document in each row and you have 10k rows. 
You should figure out what's the acceptable size of each batch and yield it in it's raw form from the extractor. 
Of course, you need to either unset `$rows` or `$rows = []` after each yield in order to avoid duplications, otherwise this array will keep growing and you are going to be processing the same results over and over. 

**Transformers**
Transformers are responsible for transforming data structures into other data structures, for example, when you are reading JSON/XML from a database, it will come as a regular string, and that's how I would throw it from the extractor. 
Then you take that string and transform it into the expected Entry type. 

From what I can see, there is no native string -> XML transformer yet, but it should be pretty straightforward to build one. 

It might sound a bit unnecessary, but this way, you keep your extractors reusable and flexible. In one of our projects, we made a mistake (in the very early days of this library) where we converted extracted data into expected entry fields directly in extractors. This ended up being a maintenance nightmare later, with too many responsibilities in one class, a lot of duplicated extractors, and much harder debugging since every other dev was implementing his own logic making data processing pipelines harder to understand. 

Much later, we decided to move away from overloading extractors with unnecessary logic, which made our data pipelines way more explicit and easier to understand/debug. 

So far, XML wasn't our main focus, except reading from plain XML reports, so we never had to implement any transformers to convert a string into XML, but I think it's something that we would need to look into. If you would like to build one and share it with the community, I can definitively guide you through and help with designing it. 

If I didn't answer all of your questions, feel free to ask more! 
I hope you find this project helpful 🍻

**Comment by norberttech** [comment]
I'm closing this issue, in case you have more questions feel free to create a new one or continue here

**Comment by norberttech** [comment]
hey @Pin0, quick update about XML. Your issue triggered me to think more about XML support in Flow. 
I noticed that XMLReaderExtractor is not really following the Extractors architecture (it was created before that design was finalized), so I had to unify it. 😊 

You can find more about it in the [pull request](https://github.com/flow-php/flow/pull/474)

I hope that will help you to come up with a simpler code that would be easier to maintain and understand.
