### ISSUE TITLE
Expression should never throw an exception but return `null` in case of failure

### ISSUE THREAD

**Issue by stloyd** [flow-php/flow#555]
> That should be the default behavior for any expression, if execution is not possible on a given cell, it should return `null` 👏

If an expression fails, it must return `null` instead of failing with an unhandled exception.

**Comment by norberttech** [comment]
> If an expression fails, it must return null instead of failing with an unhandled exception.

Just to be more accurate, if the expressions receives the input that it can't handle, then it should return null, so other expressions that are chained would also receive nulls and return just nulls. This way, we make expressions null safe because even if one of the chained expressions fails, it won't break the entire pipeline.
